### ISSUE TITLE
Remove project env yml requirement

### ISSUE THREAD

**Issue by JadenC1126** [cascode-labs/build-sphinx-action#1]
**Problem Statement**
----------------------------
Right now the yml file is a requirement for the action. We want to remove this requirement and have good defaults that are within this action's repo.

**Proposed Solution**
-------------------------------------------

- [x] Remove the yml file requirement by adding a default version to the action itself which is used if the file is not found in the repo. This will be the envs/build-docs.yml within this repo.
- [x] Document what packages are contained in the default env file.

**Alternatives Considered**
-----------------------------------------------

- Continue to require the Conda env definition yml file and fail if it isn't found.
- Commit the template yml to the repo if it's not found.

**Comment by curtisma** [comment]
@JadenC1126 Are these items done?  If so, go ahead and mark them off.

**Comment by JadenC1126** [comment]
This one is complete @curtisma 

the packages aren't really documented though. i'll add that section real quick.
