### ISSUE TITLE
Initial MVP Functionality

### ISSUE THREAD

**Issue by curtisma** [cascode-labs/build-sphinx-action#3]
**Problem Statement**
----------------------------

We have several projects that have Sphinx documentation.  We would like to have those docs easily built for each release.

**Proposed Solution**
-------------------------------------------

This action should build the sphinx documentation in the project's documentation folder.  Its structure should be modelled after [build-conda-action](https://github.com/cascode-labs/build-conda-action).

- [x] check that the necessary components are available to build the docs.  It should skip building the docs if something is missing but still exit successfully with a descriptive warning.
- [x] Setup a conda env to build the docs.  This should be defined from a env yml file, "envs/build-docs.yml"
- [x] run the "${{ inputs.docs_path}/setup_source.sh" script before building the docs
- [x] Build the docs by running the make file
- [x] Upload the docs as an artifact.

**Alternatives Considered**
-----------------------------------------------

**Proposed Action Plan**
-------------------------------
- [x] 1. Create the action that meets the requirements above
- [x] 2. Add a test workflow with each test case as a job
  - [x] Test on a GitHub-hosted runner
  - [x] Test a skipped run without a docs folder
  - [x] Each test case should check that the artifact was uploaded.
- [x] 3. Add a ReadMe modelled after the [build-conda-action](https://github.com/cascode-labs/build-conda-action) readme
  - Both readmes are based on the template [Best-README-Template](https://github.com/othneildrew/Best-README-Template)
- [x] 4. Create a release to post it on the marketplacce.

**Comment by curtisma** [comment]
@JadenC1126 
Is the fist item above, "check that the necessary components are available to build the docs...", done?  If so, go ahead and check it off and then I will work on releasing this.

**Comment by JadenC1126** [comment]
it has this: 
![image](https://user-images.githubusercontent.com/65977732/132409737-59f87d4d-5123-433d-b625-58bf2752ae86.png)

if the exit is included in a workflow will it still say it was successful?

@curtisma
